// 词语库 - 100+ 经典词对
const WORD_PAIRS = [
  { civilian: "牛奶", spy: "豆浆" },
  { civilian: "麦当劳", spy: "肯德基" },
  { civilian: "微信", spy: "QQ" },
  { civilian: "苹果", spy: "香蕉" },
  { civilian: "电影", spy: "电视剧" },
  { civilian: "咖啡", spy: "茶" },
  { civilian: "地铁", spy: "公交" },
  { civilian: "手机", spy: "电脑" },
  { civilian: "夏天", spy: "冬天" },
  { civilian: "猫", spy: "狗" },
  { civilian: "篮球", spy: "足球" },
  { civilian: "钢琴", spy: "吉他" },
  { civilian: "北京", spy: "上海" },
  { civilian: "火锅", spy: "烧烤" },
  { civilian: "眼镜", spy: "隐形眼镜" },
  { civilian: "快递", spy: "外卖" },
  { civilian: "淘宝", spy: "京东" },
  { civilian: "微信", spy: "支付宝" },
  { civilian: "奶茶", spy: "果汁" },
  { civilian: "高铁", spy: "飞机" },
  { civilian: "超市", spy: "便利店" },
  { civilian: "电影", spy: "综艺" },
  { civilian: "小说", spy: "漫画" },
  { civilian: "跑步", spy: "游泳" },
  { civilian: "早餐", spy: "午餐" },
  { civilian: "衬衫", spy: "T 恤" },
  { civilian: "雨伞", spy: "雨衣" },
  { civilian: "电梯", spy: "楼梯" },
  { civilian: "空调", spy: "风扇" },
  { civilian: "冰箱", spy: "冰柜" },
  { civilian: "洗衣", spy: "干洗" },
  { civilian: "公交卡", spy: "地铁卡" },
  { civilian: "铅笔", spy: "钢笔" },
  { civilian: "笔记本", spy: "平板" },
  { civilian: "鼠标", spy: "键盘" },
  { civilian: "耳机", spy: "音箱" },
  { civilian: "相机", spy: "摄像机" },
  { civilian: "手表", spy: "手环" },
  { civilian: "钱包", spy: "卡包" },
  { civilian: "背包", spy: "手提包" },
  { civilian: "运动鞋", spy: "皮鞋" },
  { civilian: "围巾", spy: "领带" },
  { civilian: "帽子", spy: "头盔" },
  { civilian: "手套", spy: "袖套" },
  { civilian: "牙刷", spy: "牙膏" },
  { civilian: "毛巾", spy: "浴巾" },
  { civilian: "肥皂", spy: "沐浴露" },
  { civilian: "洗发水", spy: "护发素" },
  { civilian: "化妆", spy: "护肤" },
  { civilian: "口红", spy: "唇彩" },
  { civilian: "香水", spy: "香薰" },
  { civilian: "蛋糕", spy: "面包" },
  { civilian: "饼干", spy: "薯片" },
  { civilian: "巧克力", spy: "糖果" },
  { civilian: "冰淇淋", spy: "雪糕" },
  { civilian: "汉堡", spy: "三明治" },
  { civilian: "披萨", spy: "意面" },
  { civilian: "寿司", spy: "刺身" },
  { civilian: "饺子", spy: "包子" },
  { civilian: "面条", spy: "米粉" },
  { civilian: "米饭", spy: "粥" },
  { civilian: "馒头", spy: "花卷" },
  { civilian: "油条", spy: "麻花" },
  { civilian: "豆浆", spy: "豆腐脑" },
  { civilian: "鸡蛋", spy: "鸭蛋" },
  { civilian: "牛肉", spy: "羊肉" },
  { civilian: "猪肉", spy: "鸡肉" },
  { civilian: "鱼肉", spy: "虾肉" },
  { civilian: "螃蟹", spy: "龙虾" },
  { civilian: "西瓜", spy: "哈密瓜" },
  { civilian: "葡萄", spy: "提子" },
  { civilian: "橙子", spy: "橘子" },
  { civilian: "柠檬", spy: "青柠" },
  { civilian: "草莓", spy: "蓝莓" },
  { civilian: "樱桃", spy: "车厘子" },
  { civilian: "玫瑰", spy: "月季" },
  { civilian: "百合", spy: "郁金香" },
  { civilian: "菊花", spy: "荷花" },
  { civilian: "牡丹", spy: "芍药" },
  { civilian: "松树", spy: "柏树" },
  { civilian: "柳树", spy: "杨树" },
  { civilian: "竹子", spy: "芦苇" },
  { civilian: "老虎", spy: "狮子" },
  { civilian: "大象", spy: "长颈鹿" },
  { civilian: "猴子", spy: "猩猩" },
  { civilian: "熊猫", spy: "浣熊" },
  { civilian: "兔子", spy: "松鼠" },
  { civilian: "老鹰", spy: "秃鹫" },
  { civilian: "鸽子", spy: "麻雀" },
  { civilian: "鹦鹉", spy: "八哥" },
  { civilian: "金鱼", spy: "鲤鱼" },
  { civilian: "鲨鱼", spy: "鲸鱼" },
  { civilian: "海豚", spy: "海豹" },
  { civilian: "乌龟", spy: "甲鱼" },
  { civilian: "青蛙", spy: "蟾蜍" },
  { civilian: "蝴蝶", spy: "飞蛾" },
  { civilian: "蜜蜂", spy: "黄蜂" },
  { civilian: "蜘蛛", spy: "蝎子" },
  { civilian: "蚂蚁", spy: "白蚁" },
  { civilian: "医生", spy: "护士" },
  { civilian: "老师", spy: "教授" },
  { civilian: "警察", spy: "保安" },
  { civilian: "律师", spy: "法官" },
  { civilian: "厨师", spy: "调酒师" },
  { civilian: "司机", spy: "飞行员" },
  { civilian: "记者", spy: "编辑" },
  { civilian: "演员", spy: "歌手" },
  { civilian: "作家", spy: "诗人" },
  { civilian: "画家", spy: "摄影师" },
  { civilian: "春节", spy: "元旦" },
  { civilian: "中秋", spy: "端午" },
  { civilian: "清明", spy: "重阳" },
  { civilian: "婚礼", spy: "葬礼" },
  { civilian: "生日", spy: "纪念日" },
  { civilian: "毕业", spy: "入学" },
  { civilian: "上班", spy: "下班" },
  { civilian: "开会", spy: "培训" },
  { civilian: "出差", spy: "旅游" },
  { civilian: "搬家", spy: "装修" },
  { civilian: "购物", spy: "逛街" },
  { civilian: "健身", spy: "瑜伽" },
  { civilian: "睡觉", spy: "午休" },
  { civilian: "做梦", spy: "幻想" },
  { civilian: "开心", spy: "兴奋" },
  { civilian: "难过", spy: "悲伤" },
  { civilian: "生气", spy: "愤怒" },
  { civilian: "害怕", spy: "恐惧" },
  { civilian: "惊讶", spy: "震惊" }
];

// 拼音映射（常用字）
const PINYIN_MAP = {
  "牛奶": "niú nǎi", "豆浆": "dòu jiāng", "麦当劳": "mài dāng láo", "肯德基": "kěn dé jī",
  "微信": "wēi xìn", "QQ": "QQ", "苹果": "píng guǒ", "香蕉": "xiāng jiāo",
  "电影": "diàn yǐng", "电视剧": "diàn shì jù", "咖啡": "kā fēi", "茶": "chá",
  "地铁": "dì tiě", "公交": "gōng jiāo", "手机": "shǒu jī", "电脑": "diàn nǎo",
  "夏天": "xià tiān", "冬天": "dōng tiān", "猫": "māo", "狗": "gǒu",
  "篮球": "lán qiú", "足球": "zú qiú", "钢琴": "gāng qín", "吉他": "jí tā",
  "北京": "běi jīng", "上海": "shàng hǎi", "火锅": "huǒ guō", "烧烤": "shāo kǎo",
  "眼镜": "yǎn jìng", "隐形眼镜": "yǐn xíng yǎn jìng", "快递": "kuài dì", "外卖": "wài mài",
  "淘宝": "táo bǎo", "京东": "jīng dōng", "支付宝": "zhī fù bǎo", "奶茶": "nǎi chá",
  "果汁": "guǒ zhī", "高铁": "gāo tiě", "飞机": "fēi jī", "超市": "chāo shì",
  "便利店": "biàn lì diàn", "综艺": "zōng yì", "小说": "xiǎo shuō", "漫画": "màn huà",
  "跑步": "pǎo bù", "游泳": "yóu yǒng", "早餐": "zǎo cān", "午餐": "wǔ cān",
  "衬衫": "chèn shān", "T 恤": "T xù", "雨伞": "yǔ sǎn", "雨衣": "yǔ yī",
  "电梯": "diàn tī", "楼梯": "lóu tī", "空调": "kōng tiáo", "风扇": "fēng shàn",
  "冰箱": "bīng xiāng", "冰柜": "bīng guì", "洗衣": "xǐ yī", "干洗": "gān xǐ",
  "公交卡": "gōng jiāo kǎ", "地铁卡": "dì tiě kǎ", "铅笔": "qiān bǐ", "钢笔": "gāng bǐ",
  "笔记本": "bǐ jì běn", "平板": "píng bǎn", "鼠标": "shǔ biāo", "键盘": "jiàn pán",
  "耳机": "ěr jī", "音箱": "yīn xiāng", "相机": "xiàng jī", "摄像机": "shè xiàng jī",
  "手表": "shǒu biǎo", "手环": "shǒu huán", "钱包": "qián bāo", "卡包": "kǎ bāo",
  "背包": "bēi bāo", "手提包": "shǒu tí bāo", "运动鞋": "yùn dòng xié", "皮鞋": "pí xié",
  "围巾": "wéi jīn", "领带": "lǐng dài", "帽子": "mào zi", "头盔": "tóu kuī",
  "手套": "shǒu tào", "袖套": "xiù tào", "牙刷": "yá shuā", "牙膏": "yá gāo",
  "毛巾": "máo jīn", "浴巾": "yù jīn", "肥皂": "féi zào", "沐浴露": "mù yù lù",
  "洗发水": "xǐ fà shuǐ", "护发素": "hù fà sù", "化妆": "huà zhuāng", "护肤": "hù fū",
  "口红": "kǒu hóng", "唇彩": "chún cǎi", "香水": "xiāng shuǐ", "香薰": "xiāng xūn",
  "蛋糕": "dàn gāo", "面包": "miàn bāo", "饼干": "bǐng gān", "薯片": "shǔ piàn",
  "巧克力": "qiǎo kè lì", "糖果": "táng guǒ", "冰淇淋": "bīng qí lín", "雪糕": "xuě gāo",
  "汉堡": "hàn bǎo", "三明治": "sān míng zhì", "披萨": "pī sà", "意面": "yì miàn",
  "寿司": "shòu sī", "刺身": "cì shēn", "饺子": "jiǎo zi", "包子": "bāo zi",
  "面条": "miàn tiáo", "米粉": "mǐ fěn", "米饭": "mǐ fàn", "粥": "zhōu",
  "馒头": "mán tou", "花卷": "huā juǎn", "油条": "yóu tiáo", "麻花": "má huā",
  "豆腐脑": "dòu fu nǎo", "鸡蛋": "jī dàn", "鸭蛋": "yā dàn", "牛肉": "niú ròu",
  "羊肉": "yáng ròu", "猪肉": "zhū ròu", "鸡肉": "jī ròu", "鱼肉": "yú ròu",
  "虾肉": "xiā ròu", "螃蟹": "páng xiè", "龙虾": "lóng xiā", "西瓜": "xī guā",
  "哈密瓜": "hā mì guā", "葡萄": "pú tao", "提子": "tí zi", "橙子": "chéng zi",
  "橘子": "jú zi", "柠檬": "níng méng", "青柠": "qīng níng", "草莓": "cǎo méi",
  "蓝莓": "lán méi", "樱桃": "yīng táo", "车厘子": "chē lí zi", "玫瑰": "méi gui",
  "月季": "yuè jì", "百合": "bǎi hé", "郁金香": "yù jīn xiāng", "菊花": "jú huā",
  "荷花": "hé huā", "牡丹": "mǔ dān", "芍药": "sháo yao", "松树": "sōng shù",
  "柏树": "bǎi shù", "柳树": "liǔ shù", "杨树": "yáng shù", "竹子": "zhú zi",
  "芦苇": "lú wěi", "老虎": "lǎo hǔ", "狮子": "shī zi", "大象": "dà xiàng",
  "长颈鹿": "cháng jǐng lù", "猴子": "hóu zi", "猩猩": "xīng xing", "熊猫": "xióng māo",
  "浣熊": "huàn xióng", "兔子": "tù zi", "松鼠": "sōng shǔ", "老鹰": "lǎo yīng",
  "秃鹫": "tū jiù", "鸽子": "gē zi", "麻雀": "má què", "鹦鹉": "yīng wǔ",
  "八哥": "bā ge", "金鱼": "jīn yú", "鲤鱼": "lǐ yú", "鲨鱼": "shā yú",
  "鲸鱼": "jīng yú", "海豚": "hǎi tún", "海豹": "hǎi bào", "乌龟": "wū guī",
  "甲鱼": "jiǎ yú", "青蛙": "qīng wā", "蟾蜍": "chán chú", "蝴蝶": "hú dié",
  "飞蛾": "fēi é", "蜜蜂": "mì fēng", "黄蜂": "huáng fēng", "蜘蛛": "zhī zhū",
  "蝎子": "xiē zi", "蚂蚁": "mǎ yǐ", "白蚁": "bái yǐ", "医生": "yī shēng",
  "护士": "hù shi", "老师": "lǎo shī", "教授": "jiào shòu", "警察": "jǐng chá",
  "保安": "bǎo ān", "律师": "lǜ shī", "法官": "fǎ guān", "厨师": "chú shī",
  "调酒师": "tiáo jiǔ shī", "司机": "sī jī", "飞行员": "fēi xíng yuán", "记者": "jì zhě",
  "编辑": "biān jí", "演员": "yǎn yuán", "歌手": "gē shǒu", "作家": "zuò jiā",
  "诗人": "shī rén", "画家": "huà jiā", "摄影师": "shè yǐng shī", "春节": "chūn jié",
  "元旦": "yuán dàn", "中秋": "zhōng qiū", "端午": "duān wǔ", "清明": "qīng míng",
  "重阳": "chóng yáng", "婚礼": "hūn lǐ", "葬礼": "zàng lǐ", "生日": "shēng rì",
  "纪念日": "jì niàn rì", "毕业": "bì yè", "入学": "rù xué", "上班": "shàng bān",
  "下班": "xià bān", "开会": "kāi huì", "培训": "péi xùn", "出差": "chū chāi",
  "旅游": "lǚ yóu", "搬家": "bān jiā", "装修": "zhuāng xiū", "购物": "gòu wù",
  "逛街": "guàng jiē", "健身": "jiàn shēn", "瑜伽": "yú jiā", "睡觉": "shuì jiào",
  "午休": "wǔ xiū", "做梦": "zuò mèng", "幻想": "huàn xiǎng", "开心": "kāi xīn",
  "兴奋": "xīng fèn", "难过": "nán guò", "悲伤": "bēi shāng", "生气": "shēng qì",
  "愤怒": "fèn nù", "害怕": "hài pà", "恐惧": "kǒng jù", "惊讶": "jīng yà",
  "震惊": "zhèn jīng"
};

// 获取拼音
function getPinyin(word) {
  return PINYIN_MAP[word] || "";
}

// 随机获取词对
function getRandomWordPair() {
  const randomIndex = Math.floor(Math.random() * WORD_PAIRS.length);
  return WORD_PAIRS[randomIndex];
}

// 随机填充词语
function randomWords() {
  const pair = getRandomWordPair();
  document.getElementById('civilian-word').value = pair.civilian;
  document.getElementById('spy-word').value = pair.spy;
  
  // 更新拼音显示
  document.getElementById('civilian-pinyin').textContent = getPinyin(pair.civilian);
  document.getElementById('spy-pinyin').textContent = getPinyin(pair.spy);
}

// 初始化时随机填充
window.addEventListener('DOMContentLoaded', () => {
  randomWords();
});
